version: "3.8"
services:
  frontend:
    container_name: frontend
    restart: always
    stdin_open: true
    tty: true
    build:
      context: ./
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
